{% set name = "dvc" %}
{% set version = "2.52.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a527a7b833cec0e2f1b235b6b37299d3b817f7d6248f19e847a9bfba2eb013a8
  patches:
    - build.patch

build:
  noarch: python
  number: 0
  entry_points:
    - dvc = dvc.main:main
  script:
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=7
  run:
    - python >=3.8
    - colorama >=0.3.9
    - configobj >=5.0.6
    - voluptuous >=0.11.7
    - requests >=2.22.0
    - grandalf >=0.7,<1
    - distro >=1.3.0
    - platformdirs <4,>=3.1.1
    - ruamel.yaml >=0.17.11
    - tomlkit >=0.11.1
    - funcy >=1.14
    - pathspec >=0.10.3
    - shortuuid >=0.5.0
    - tqdm >=4.63.1,<5
    - packaging >=19.0
    - zc.lockfile >=1.2.1
    - flufl.lock >=5
    - networkx >=2.5
    - psutil >=5.8.0
    - pydot >=1.2.4
    - importlib_resources >=5.2.2
    - flatten-dict >=0.4.1,<1
    - tabulate >=0.8.7
    - pygtrie >=2.3.2
    - dpath >=2.0.2,<3
    - shtab >=1.3.4,<2
    - rich >=10.13.0
    - pyparsing >=2.4.7
    - typing_extensions >=3.7.4
    - scmrepo >=0.1.17,<1
    - dvc-render >=0.1.2
    - dvc-data >=0.46.0,<0.47
    - dvc-http
    - dvc-task >=0.2.0,<1
    - hydra-core >=1.1.0
    - iterative-telemetry >=0.0.7
    - dvc-studio-client >=0.6.1,<1

# Base package supports dvc, but only supports built-in remotes
test:
  requires:
    - git
    - pip
  imports:
    - dvc
    - dvc.repo
  commands:
    - pip check
    - dvc version
    - dvc version | grep {{ version }}
    - dvc version | grep https

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DVC tracks ML models and data sets

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - daavoo
    - shcheklein
    - efiop
    - skshetry
    - pmrowla
    - weiji14
